### create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "tienvv123456@gmail.com",
    "password": "123456"
}

### sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "tienvv123456@gmail.com",
    "password": "123456"
}


### Sign out
POST http://localhost:3000/auth/signout

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with a given ID
GET http://localhost:3000/auth/3


### Find a particular user with a given Email
GET http://localhost:3000/auth?email=sdfasdf@gmail.com

### Remove a particular user with a given ID
DELETE http://localhost:3000/auth/1

### Update a particular user with a given ID
PATCH  http://localhost:3000/auth/2
content-type: application/json

{
    "email": "aaa@aaa.com"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors
